### ISSUE TITLE
Artifactory metrics not being showed 

### ISSUE THREAD

**Issue by carmenmokz** [jfrog/log-analytics-prometheus#15]
Hi,

I was trying to use the fluentd as a exporter of the JFrog Artifactory metrics to use with prometheus. I followed the instructions of the readme file:

> 2. Use the appropriate FluentD configuration file and copy it to /etc/td-agent/td-agent.conf.
>     fluent.conf.rt - Artifactory version 7 server
>     fluent.conf.rt6 - Artifactory version 6 server
>     fluent.conf.xray - Xray server (3.x+)
> 3. Restart td-agent.

But this doesn't show the metrics when I display it on the browser by using the IP and the port that is specified.

![image](https://user-images.githubusercontent.com/9439071/101545797-698d0480-396d-11eb-8022-46d28d011cee.png)

But, if I run the the td-agent with the following command:

`td-agent -c fluent.conf.rt6`

It works as expected, as is shown on the following screenshot.

![image](https://user-images.githubusercontent.com/9439071/101545664-38143900-396d-11eb-9b7b-9da2b912daeb.png)

**Comment by peters95** [comment]
Hi @carmenmokz 

Can you explain what version of Artifactory you are trying to use this on?

If it is RT 6.x then this would make sense as that is the correct configuration file for RT6.x platforms.

**Comment by carmenmokz** [comment]
Hi @peters95 !
I managed to get the metrics to show. It seems that the environment metrics were not being detected, therefore, the used path for ARTIFACTORY_HOME was not correct.
Do you know why does the happens?

**Comment by peters95** [comment]
This may happen depending upon the version you are running. Can you help answer the two questions below to narrow this down...

a) How did you deploy Artifactory?
  Zip installer, Package based (RPM, DEB, etc), Docker, Helm, Cloud marketplace, etc...

b) What version of Artifactory did you deploy?


Thanks!

**Comment by carmenmokz** [comment]
a) It was installed using RPM with an ansible role
b) Artifactory OSS 6.10.0

**Comment by peters95** [comment]
Hi Carmen,

We only certified Artifactory 6.x for Artifactory Pro / Pro + . Please consider upgrading to Artifactory 7.x we have validated that Artifactory 7.x OSS works with our integration. This is likely why you have experienced these issues.

Given we do not officially support Artifactory 6.x OSS I will close this ticket. Feel free to reach out again if you experience any issues with 7.x OSS

**Comment by 77aaqib** [comment]
HI Team,

We tried same steps but we are not getting jfrog metrics. We have antifactory 6.0 and hosted on windows server. Antifactory is in H drive is any steps or suggestion to be followed for windows antifactory.?or why data is not coming.
![art1x](https://user-images.githubusercontent.com/77726772/162901976-d06654a8-7588-4e8a-b58c-bab82d414a6c.JPG)
