### ISSUE TITLE
Support for Kustomize

### ISSUE THREAD

**Issue by kchenye-bitgo** [jfrog/log-analytics-prometheus#27]
Hello,

At the moment we deploy Artifactory HA using Kustomize and other plugins such as khelm and ksops. That being said, there are several resources in this project that can be bundled perfectly as a kustomize component:

- the custom init container and custom sidecar container can be turned into patches for primary and member STS manifests
- new resources (service and serviceMonitor) can be added as plain resources
- `fluent.conf.rt` and the grafana dashboards can be placed into configMaps via `ConfigMapGenerators`

Would it be possible to provide the contents of this repo as a kustomize component?

**Comment by betarelease** [comment]
Hi @kchenye-bitgo We do not have any plans changing this at this moment. But if you are willing to send us a PR we will work on merging it after sufficient testing.
