### ISSUE TITLE
Use FluentD as a pod

### ISSUE THREAD

**Issue by laith-leo** [jfrog/log-analytics-prometheus#7]
I need to use FluentD as a separate deployment in EKS using HELM, in other words, how can I use the same configurations of this [repo](https://github.com/jfrog/log-analytics-prometheus/tree/JFProductEnv#fluentd-configuration) but with using the FluentD HELM chart? Where to copy the contents of [fluent.conf.rt ](https://github.com/jfrog/log-analytics-prometheus/blob/JFProductEnv/fluent.conf.rt) in the HELM chart of FluentD?

**Comment by peters95** [comment]
@laith-leo prometheus has been integrated into the artifactory and artifactory-ha helm charts on PR# [1094](https://github.com/jfrog/charts/pull/1094). let us know if this does not cover your needs. Thank you!

**Comment by laith-leo** [comment]
@peters95 thanks peter, in fact, i want to use fluentd (as a pod), and not sure how/where to use fluent.conf.rt so it sends the jfrog logs to prometheus then i can visualize it in grafana.

**Comment by peters95** [comment]
@laith-leo fluentd is already running as a sidecar in the same pod so it has access to the mount of the artifactory container to read the log files. Is this what you want or are you asking for something else?

**Comment by peters95** [comment]
@laith-leo please respond to the above if possible or we will close this issue for inactivity in a few days.
